import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { appListV1 } from "./api/appList/v1";
import SideBar from "./components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {availableFilters} = await appListV1.getLayoutData()

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid grid-cols-[200px,_1fr] h-full gap-8">
          <SideBar availableFilters={availableFilters} />
          {children} 
        </main>
      </body> 
    </html>
  );
}
